title: ESP32-C3 Breadboard Adapter
description: ESP32 IoT gadgets by Alexander B
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
baseurl: "/ESP32-C3_Breadboard-Adapter" # the subpath of your site, e.g. /blog
url: "https://alexandrebobkov.github.io/" # the base hostname & protocol for your site
permalink: /:month-:day-:year/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

kramdown:
  syntax_highlighter: coderay

#header_pages:
#  - about.md

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
