title: ESP32-S3 Uno DevBoard
description: Build your prototypes with a human touch.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
#github hosted
#baseurl: "/ESP32-S3_Arduino-Uno" # the subpath of your site, e.g. /blog
#url: "https://alexandrebobkov.github.io/" # the base hostname & protocol for your site
baseurl: "/"
url: "https://devboard.techquadbit.net/"
permalink: /:month-:day-:year/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

kramdown:
  syntax_highlighter: coderay

header_pages:
  - specs.md
  - schematic.md

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
